disabled_rules: # rule identifiers to exclude from running
    - colon
    - line_length
    - file_length
    - shorthand_operator
    - type_body_length
    - function_body_length
    - variable_name
    - cyclomatic_complexity
    - type_name
    - function_parameter_count
    - implicit_getter
    - control_statement
    - redundant_string_enum_value
    - syntactic_sugar
    - for_where
    - unused_optional_binding
    - todo
    - large_tuple
    - generic_type_name
    - mark
    - empty_enum_arguments
    - block_based_kvo
    - class_delegate_protocol
    - switch_case_alignment
    - unneeded_break_in_switch
    - multiple_closures_with_trailing_closure
    - nesting
    - force_cast
    
opt_in_rules: # some rules are only opt-in
#  - force_unwrapping

#included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.
